project1_booking/booking/urls.py
from django.contrib.auth.views import LoginView, LogoutView  
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('', views.MeetingCalendar.as_view(), name='calendar'),
    path('<int:year>/<int:month>/<int:day>/', views.MeetingCalendar.as_view(), name='calendar'),
    path('<int:year>/<int:month>/<int:day>/<int:hour>/', views.Booking.as_view(), name='booking'),
    path('login/', LoginView.as_view(template_name='admin/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('staffpage/', views.StaffPage.as_view(), name='staff_page'),
    path('staffpage/calendar/', views.StaffCalendar.as_view(), name='staff_calendar'),
    path('staffpage/calendar/<int:year>/<int:month>/<int:day>/', views.StaffCalendar.as_view(), name='staff_calendar'),
    path('staffpage/config/<int:year>/<int:month>/<int:day>/', views.DayDetail.as_view(), name='day_detail'),
    path('staffpage/schedule/<int:pk>/', views.StaffSchedule.as_view(), name='staff_schedule'),
    path('staffpage/schedule/<int:pk>/delete/', views.ScheduleDelete.as_view(), name='schedule_delete'),
    path('staffpage/rest/add/<int:year>/<int:month>/<int:day>/<int:hour>/', views.staff_rest_add, name='staff_rest_add'),
]

project1_booking/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('booking.urls'))
]

project1_booking/booking/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Schedule(models.Model):
    """予約スケジュール"""
    start     = models.DateTimeField('開始時間')
    class_num = models.IntegerField(default=14)   #組
    id_num    = models.IntegerField(default=1)    #番号
    name      = models.CharField('予約者名', max_length=255)

    def __str__(self):
        start = timezone.localtime(self.start).strftime('%Y/%m/%d %H:%M:%S')

        #ex). 山田太郎,14組1番:2025/04/01 12:00:00
        return f'{self.name},{self.class_num} 組 {self.id_num} 番 : {start}'

project1_booking/booking/views.py
import datetime
from django.shortcuts import render
from django.conf import settings
from django.db.models import Q
from django.shortcuts import get_object_or_404,redirect
from django.utils import timezone
from django.views import generic
from .models import Schedule
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.views.decorators.http import require_POST


class MeetingCalendar(generic.TemplateView):
    template_name = 'booking/calendar.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        today = datetime.date.today()

        # どの日を基準にカレンダーを表示するかの処理。
        # 年月日の指定があればそれを、なければ今日からの表示。
        year  = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day   = self.kwargs.get('day')
        if year and month and day:
            base_date = datetime.date(year=year, month=month, day=day)
        else:
            base_date = today

        # カレンダーは1週間分表示するので、基準日から1週間の日付を作成しておく
        days = [base_date + datetime.timedelta(days=day) for day in range(7)]
        start_day = days[0]
        end_day = days[-1]

        # 13時から19時まで1時間刻み、1週間分の、値がTrueなカレンダーを作る
        calendar = {}
        for hour in range(13, 20):
            row = {}
            for day in days:
                row[day] = True
            calendar[hour] = row

        # カレンダー表示する最初と最後の日時の間にある予約を取得する
        start_time = datetime.datetime.combine(start_day, datetime.time(hour=12, minute=59, second=59))
        end_time   = datetime.datetime.combine(end_day,   datetime.time(hour=20, minute=0, second=0))


        for schedule in Schedule.objects.exclude(Q(start__gt=end_time) | Q(start__lt=start_time)):
            local_dt = timezone.localtime(schedule.start)
            booking_date = local_dt.date()
            booking_hour = local_dt.hour
            if booking_hour in calendar and booking_date in calendar[booking_hour]:
                calendar[booking_hour][booking_date] = False

        context['calendar'] = calendar
        context['days'] = days
        context['start_day'] = start_day
        context['end_day'] = end_day
        context['before'] = days[0] - datetime.timedelta(days=7)
        context['next'] = days[-1] + datetime.timedelta(days=1)
        context['today'] = today
        context['public_holidays'] = settings.PUBLIC_HOLIDAYS
        return context

class Booking(generic.CreateView):
    model = Schedule
    fields = ('name','class_num','id_num')
    template_name = 'booking/booking.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):

        year  = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day   = self.kwargs.get('day')
        hour  = self.kwargs.get('hour')
        start = datetime.datetime(year=year, month=month, day=day, hour=hour)

        if Schedule.objects.filter( start=start).exists():
            messages.error(self.request, 'ダブルブッキングしてしまいました。別の日時はどうですか。')
        else:
            schedule = form.save(commit=False)
            schedule.start = start
            schedule.save()
        return redirect('booking:calendar')

class StaffPage(LoginRequiredMixin, generic.TemplateView):
    template_name = 'booking/staff.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['schedule_list'] = Schedule.objects.filter(start__gte=timezone.now()).order_by('start')
        return context

class StaffCalendar(MeetingCalendar):
    template_name = 'booking/staff_calendar.html'

class DayDetail(generic.TemplateView):
    template_name = 'booking/day_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        date = datetime.date(year=year, month=month, day=day)

        # 9時から17時まで1時間刻みのカレンダーを作る
        calendar = {}
        for hour in range(13, 20):
            calendar[hour] = []

        # カレンダー表示する最初と最後の日時の間にある予約を取得する
        start_time = datetime.datetime.combine(date, datetime.time(hour=12, minute=59, second=59))
        end_time = datetime.datetime.combine(date, datetime.time(hour=20, minute=0, second=0))
        for schedule in Schedule.objects.exclude(Q(start__gt=end_time) | Q(start__lt=start_time)):
            local_dt = timezone.localtime(schedule.start)
            booking_date = local_dt.date()
            booking_hour = local_dt.hour
            if booking_hour in calendar:
                calendar[booking_hour].append(schedule)

        context['calendar'] = calendar
        return context

class StaffSchedule(generic.UpdateView):
    model = Schedule
    fields = ('start', 'name')
    success_url = reverse_lazy('booking:staff_page')

class ScheduleDelete(generic.DeleteView):
    model = Schedule
    success_url = reverse_lazy('booking:staff_page')

@require_POST
def staff_rest_add(request,year, month, day, hour):
    
    start = datetime.datetime(year=year, month=month, day=day, hour=hour)
    Schedule.objects.create(start=start, class_num=0, id_num = 0,name='お休み(システムによる追加)')
    return redirect('booking:day_detail', year=year, month=month, day=day)

project1_booking/booking/templates/booking/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>面談予約サイト</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'booking/style.css' %}">
</head>

<body>

<nav>
    <a href="{% url 'booking:calendar' %}">Home</a>
    {% if user.is_authenticated %}
        <a href="{% url 'booking:staff_page' %}">StaffPage</a>
        <form method="post" action="{% url 'booking:logout' %}" style="display:inline;">
            {% csrf_token %}
            <button type="submit" style="background:none; border:none; color:blue; cursor:pointer;">
                Logout
            </button>
        </form>
    {% else %}
        <a href="{% url 'booking:login' %}">Login</a>
    {% endif %}
</nav>

{% for message in messages %}
    <p> {{ message }}</p>
{% endfor %}

{% block content %}{% endblock %}

</body>
</html>

project1_booking/booking/templates/booking/booking.html
{% extends 'booking/base.html' %}

{% block content %}
    <p>{{ view.kwargs.year }}年{{ view.kwargs.month }}月{{ view.kwargs.day }}日 {{ view.kwargs.hour }}時に予約</p>
    <form action="" method="POST">
        <div class="form-example">
            <label for="name">名前: </label>
            <input type="text" name="name" id="name" required />
        </div>
        <div class="form-example">
            <label for="class_num">組　: </label>
            <input type="number" name="class_num" id="class_num" required />
        </div>
        <div class="form-example">
            <label for="id_num">番号: </label>
            <input type="number" name="id_num" id="id_num" required />
        </div>
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
{% endblock %}

project1_booking/booking/templates/booking/calendar.html
{% extends 'booking/base.html' %}

{% block content %}

    <h1>面談予約サイト</h1>
    <p>{{ start_day }} - {{ end_day }}</p>
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%" border="1">
        <tr>
            <td><a href="{% url 'booking:calendar' before.year before.month before.day %}">前週</a></td>
            {% for day in days %}
                {% if day in public_holidays %}
                    <th style="color: red">{{ day | date:"d(D)" }}</th>
                {% elif day.weekday == 5 %}
                    <th style="color: blue;">{{ day | date:"d(D)" }}</th>
                {% elif day.weekday == 6 %}
                    <th style="color: red;">{{ day | date:"d(D)" }}</th>
                {% else %}
                    <th>{{ day | date:"d(D)" }}</th>
                {% endif %}
            {% endfor %}
            <td><a href="{% url 'booking:calendar' next.year next.month next.day %}">次週</a></td>
        </tr>

        {% for hour, schedules in calendar.items %}
            <tr style="font-size:12px">
                <td>
                    {{ hour }}:00
                </td>
                {% for dt, book in schedules.items %}
                    <td>
                        {% if dt <= today %}
                            <span class="symbol disabled">-</span>
                        {% elif book %}
                            <a href="{% url 'booking:booking' dt.year dt.month dt.day hour %}" class="symbol available">○</a>
                        {% else %}
                            <span class="symbol unavailable">×</span>
                        {% endif %}
                    </td>

                {% endfor %}
                <td>
                    {{ hour }}:00
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

project1_booking/booking/templates/booking/day_detail.html
{% extends 'booking/base.html' %}

{% block content %}

    <p>{{ view.kwargs.year }}年{{ view.kwargs.month }}月{{ view.kwargs.day }}日の予約一覧</p>
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%" border="1">
        {% for hour, schedules in calendar.items %}
            <tr style="font-size:12px">
                <td>
                    {{ hour }}:00
                </td>
                <td>
                    {% if schedules %}
                        {% for s in schedules %}
                        <a href="{% url 'booking:staff_schedule' s.pk%}">{{ s.class_num }}組{{s.id_num}}番：{{s.name}} </a>
                        {% endfor %}
                    {% else %}
                        <form action="{% url 'booking:staff_rest_add' view.kwargs.year view.kwargs.month view.kwargs.day hour %}"
                              method="POST">
                            {% csrf_token %}
                            <button type="submit">お休みにする</button>
                        </form>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

project1_booking/booking/templates/booking/schedule_form.html
{% extends 'booking/base.html' %}

{% block content %}

    <form action="" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">変更</button>
    </form>
    <hr>
    <form action="{% url 'booking:schedule_delete' schedule.pk%}" method="POST">
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
{% endblock %}

project1_booking/booking/templates/booking/staff.html
{% extends 'booking/base.html' %}

{% block content %}
    
    <ul>
        <li><a href="{% url 'booking:staff_calendar' %}">カレンダー</a></li>
    </ul>
    <h2>直近の予約</h2>
    <ul>
        {% for schedule in schedule_list %}
            {%if schedule.class_num != 0%}
                <li><a href="{% url 'booking:staff_schedule' schedule.pk%}">{{ schedule }}</li>
            {%endif%}
        {% empty %}
            <li>予約はありません。</li>
        {% endfor %}
    </ul>
{% endblock %}

project1_booking/booking/templates/booking/staff_calendar.html
{% extends 'booking/base.html' %}

{% block content %}

    <p>{{ start_day }} - {{ end_day }}</p>
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%" border="1">
        <tr>
            <td><a href="{% url 'booking:staff_calendar' before.year before.month before.day %}">前週</a></td>
            {% for day in days %}
                {% if day in public_holidays %}
                    <th style="color: red">{{ day | date:"d(D)" }}
                {% elif day.weekday == 5 %}
                    <th style="color: blue;">{{ day | date:"d(D)" }}
                {% elif day.weekday == 6 %}
                    <th style="color: red;">{{ day | date:"d(D)" }}
                {% else %}
                    <th>{{ day | date:"d(D)" }}
                {% endif %}
                <br><a href="{% url 'booking:day_detail' day.year day.month day.day %}">詳細</a>
            {% endfor %}
            <td><a href="{% url 'booking:staff_calendar'  next.year next.month next.day %}">次週</a></td>
        </tr>

        {% for hour, schedules in calendar.items %}
            <tr style="font-size:12px">
                <td>
                    {{ hour }}:00
                </td>
                {% for dt, book in schedules.items %}
                    <td>
                        {% if book %}
                            ○
                        {% else %}
                            ×
                        {% endif %}
                    </td>

                {% endfor %}
                <td>
                    {{ hour }}:00
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}